export const ActionTypes = {
    SET_PRODUCTS : 'SET_PRODUCTS',
    SELECTED_PRODUCT : 'SELECTED_PRODUCT',
    REMOVE_SELECTED_PRODUCT : 'REMOVE_SELECTED_PRODUCT',
    SET_CATEGORIES : 'SET_CATEGORIES',
    SELECTED_CATEGORIES : 'SELECTED_CATEGORIES',
    REMOVE_SELECTED_CATEGORIES : 'REMOVE_SELECTED_CATEGORIES',
    FILTER_PRODUCT_BY_ID : 'FILTER_PRODUCT_BY_ID',
    FILTER_PRODUCT_BY_RATE : 'FILTER_PRODUCT_BY_RATE',
    FILTER_PRODUCT_BY_STOCK : 'FILTER_PRODUCT_BY_STOCK',
    FILTER_PRODUCT_BY_PRICE_DOWN : 'FILTER_PRODUCT_BY_PRICE_DOWN',
    FILTER_PRODUCT_BY_PRICE_UP : 'FILTER_PRODUCT_BY_PRICE_UP',
}